final Map<int, String>  error_codes = {
  0: 'Success',
  1: 'No login',
  2: 'No method',
  3: 'Error path',
  4: 'Error format',
  5: 'Error parameter',
  6: 'Permission not allowed',
  7: 'Upload file error',
  8: 'File not found',
  10: 'Account password error',
  11: 'Token expire',
  12: 'Token refresh fail',
  13: 'Account disabled',
  14: 'Active code expire',
  15: 'Account not active',
  20: 'Account exists',
  30: 'No app',
  31: 'Permission not allowed',
  32: 'Not allow server forward',
  40: 'Permission not allowed (account)',
  41: 'Account not found',
  42: 'Account activated',
  43: 'Send verification code frequently',
  50: 'Permission not allowed (group)',
  51: 'Group not found',
  101: 'No device',
  102: 'Permission not allowed (device)',
  103: 'Send command fail',
  104: 'No IR control',
  105: 'No IR control key',
  199: 'Update data fail',
  106: 'Device exists',
  107: 'No user ID',
  108: 'Gateway not found',
  109: 'Active code error',
  110: 'Too many sub-devices',
  111: 'No device model',
  112: 'Command cached',
  501: 'No trigger',
  502: 'Add failed',
  503: 'Update failed',
  504: 'Permission not allowed (trigger action)',
  601: 'No access code',
  701: 'No user token data',
  801: 'No script',
  802: 'Permission not allowed (script)',
  803: 'Too many requests (script)',
  9999: 'Other system error',
  9998: 'Other path error',
  9997: 'Other 500 error',
  9996: 'Error confirm code',
  7001: 'App ID error (internal service)',
  7002: 'User ID error (internal service)',
  7003: 'Device ID error (internal service)',
  7004: 'Permission error (internal service)',
};