// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJc7tQFFRGl43-DzliBXTpOshOr102_4',
    appId: '1:39825301196:web:fa1ecab406e1f195a8ec69',
    messagingSenderId: '39825301196',
    projectId: 'ihouseems',
    authDomain: 'ihouseems.firebaseapp.com',
    storageBucket: 'ihouseems.appspot.com',
    measurementId: 'G-PF191CVB7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATcK0nbEu8zIRMuAVW_0dvHM_IwvZKSB4',
    appId: '1:39825301196:android:c5e343cdc238c87ea8ec69',
    messagingSenderId: '39825301196',
    projectId: 'ihouseems',
    storageBucket: 'ihouseems.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjVu8UPbRbbOO4YNGPVbvo4fbMt2AR8eE',
    appId: '1:39825301196:ios:66747cb33b8bc30fa8ec69',
    messagingSenderId: '39825301196',
    projectId: 'ihouseems',
    storageBucket: 'ihouseems.appspot.com',
    androidClientId: '39825301196-8dv101qdule7aarsi2tv42k36q88arh2.apps.googleusercontent.com',
    iosClientId: '39825301196-gv730bqig7recoadd1orvtjhaso3841p.apps.googleusercontent.com',
    iosBundleId: 'com.cwo.ihouseEMS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjVu8UPbRbbOO4YNGPVbvo4fbMt2AR8eE',
    appId: '1:39825301196:ios:1152890eb36511a3a8ec69',
    messagingSenderId: '39825301196',
    projectId: 'ihouseems',
    storageBucket: 'ihouseems.appspot.com',
    androidClientId: '39825301196-8dv101qdule7aarsi2tv42k36q88arh2.apps.googleusercontent.com',
    iosClientId: '39825301196-oqid8j7ov64hb2gs6s79efebcn512eni.apps.googleusercontent.com',
    iosBundleId: 'com.example.emsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIJc7tQFFRGl43-DzliBXTpOshOr102_4',
    appId: '1:39825301196:web:b8606fb8dfd4df07a8ec69',
    messagingSenderId: '39825301196',
    projectId: 'ihouseems',
    authDomain: 'ihouseems.firebaseapp.com',
    storageBucket: 'ihouseems.appspot.com',
    measurementId: 'G-02VR7D2HS9',
  );

}